on:
  push:
    branches: [main, master]

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
         remotes::install_deps(dependencies = TRUE)
         remotes::install_cran('rcmdcheck')
         remotes::install_cran('devtools')
         remotes::install_local()
         shell: Rscript {0}

      - name: Install rsconnect
        run: install.packages('rsconnect')
        shell: Rscript {0}

      - name: Authorize and deploy app
        env:
          # Provide your app name, account name, and server to be deployed below
          APPNAME: shinyscholar
          ACCOUNT: simonsmart
          SERVER: shinyapps.io # server to deploy
        run: |
          rsconnect::setAccountInfo("simonsmart", "${{ secrets.SHINYAPPS_TOKEN }}", "${{ secrets.SHINYAPPS_SECRET }}")
          rsconnect::deployApp(appName = "${{ env.APPNAME }}", account = "${{ env.ACCOUNT }}", server = "${{ env.SERVER }}")
        shell: Rscript {0}
